import type { NextPage } from 'next';
import Head from 'next/head';

const Artikel: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-gray-400'>
        <h1>Artikel</h1>
      </main>
      <footer>
        <p>Binarycult website</p>
      </footer>
    </div>
  );
};

export default Artikel;
