import type { NextPage } from 'next';
import Head from 'next/head';
import { Slider } from '../components/slider';

const images = [
  { href: '/', src: '/1.png' },
  { href: '/', src: '/2.png' },
  { href: '/', src: '/3.png' },
  { href: '/', src: '/4.png' },
  { href: '/', src: '/5.png' },
  { href: '/', src: '/vercel.svg' },
];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-gray-400'>
        <h1>Koffer voller Immajung</h1>
      </main>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, quia. Aspernatur distinctio, tenetur natus
        molestias modi magni deserunt culpa laborum inventore expedita nobis quidem! In commodi soluta doloremque vero
        explicabo? Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, quia. Aspernatur distinctio,
        tenetur natus molestias modi magni deserunt culpa laborum inventore expedita nobis quidem! In commodi soluta
        doloremque vero explicabo? Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, quia.
        Aspernatur distinctio, tenetur natus molestias modi magni deserunt culpa laborum inventore expedita nobis
        quidem! In commodi soluta doloremque vero explicabo? Lorem ipsum dolor sit amet consectetur adipisicing elit.
        Praesentium, quia. Aspernatur distinctio, tenetur natus molestias modi magni deserunt culpa laborum inventore
        expedita nobis quidem! In commodi soluta doloremque vero explicabo? Lorem ipsum dolor sit amet consectetur
        adipisicing elit. Praesentium, quia. Aspernatur distinctio, tenetur natus molestias modi magni deserunt culpa
        laborum inventore expedita nobis quidem! In commodi soluta doloremque vero explicabo? Lorem ipsum dolor sit amet
        consectetur adipisicing elit. Praesentium, quia. Aspernatur distinctio, tenetur natus molestias modi magni
        deserunt culpa laborum inventore expedita nobis quidem! In commodi soluta doloremque vero explicabo? Lorem ipsum
        dolor sit amet consectetur adipisicing elit. Praesentium, quia. Aspernatur distinctio, tenetur natus molestias
        modi magni deserunt culpa laborum inventore expedita nobis quidem! In commodi soluta doloremque vero explicabo?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, quia. Aspernatur distinctio, tenetur natus
        molestias modi magni deserunt culpa laborum inventore expedita nobis quidem! In commodi soluta doloremque vero
        explicabo? Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, quia. Aspernatur distinctio,
        tenetur natus molestias modi magni deserunt culpa laborum inventore expedita nobis quidem! In commodi soluta
        doloremque vero explicabo? Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, quia.
        Aspernatur distinctio, tenetur natus molestias modi magni deserunt culpa laborum inventore expedita nobis
        quidem! In commodi soluta doloremque vero explicabo? Lorem ipsum dolor sit amet consectetur adipisicing elit.
        Praesentium, quia. Aspernatur distinctio, tenetur natus molestias modi magni deserunt culpa laborum inventore
        expedita nobis quidem! In commodi soluta doloremque vero explicabo? Lorem ipsum dolor sit amet consectetur
        adipisicing elit. Praesentium, quia. Aspernatur distinctio, tenetur natus molestias modi magni deserunt culpa
        laborum inventore expedita nobis quidem! In commodi soluta doloremque vero explicabo?
      </p>
      <Slider images={images} />
      <footer>
        <p>Binarycult website</p>
      </footer>
    </div>
  );
};

export default Home;
